branch-defaults:
  master:
    environment: simple-env
    group_suffix: null
environment-defaults:
  simple:
    branch: null
    repository: null
  simple-dev:
    branch: null
    repository: null
  simple-env:
    branch: null
    repository: null
global:
  application_name: simple
  branch: null
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git
